language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: 3.8-dev
      env: TOXENV=py38-dev
      dist: xenial
      sudo: true
    #powerjobs
    - python: 2.7
      env: TOXENV=py27
      arch: ppc64le
    - python: 3.6
      env: TOXENV=py36
      arch: ppc64le
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      arch: ppc64le
      sudo: true
    - python: 3.8-dev
      env: TOXENV=py38-dev
      dist: xenial
      sudo: true
      arch: ppc64le
   
  allow_failures:
    - env: TOXENV=py38-dev

before_install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py check --strict

script:
  - make test

after_success:
  - coveralls
